---
test-cases: /home/user/test-cases
comparators:
  ProvToolboxComparator:
    class: prov_interop.provtoolbox.comparator.ProvToolboxComparator
    executable: provconvert
    arguments: -infile FILE1 -compare FILE2
    # Formats must be in set [json, provn, provx, trig, ttl]
    formats: [provn, trig, provx, json]