---
ProvTranslatorConverter:
  url: https://provenance.ecs.soton.ac.uk/validator/provapi/documents/
  # Formats must be in set [json, provn, provx, trig, ttl]
  input-formats: [provn, ttl, trig, provx, json]
  output-formats: [provn, ttl, trig, provx, json]
  skip-tests: []
